<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void

    {
        $coat = Category::where('name', 'Coats')->first();
        $Puffer = Category::where('name', 'Puffer')->first();
        $Knitwear = Category::where('name', 'Knitwear')->first();
        $Hoodies = Category::where('name', 'Hoodies')->first();
        $Dresses = Category::where('name', 'Dresses')->first();
      
        $products = [
     

    // Category 6 - Puffer
    ['image' => 'bub1.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129 ,
     'original_price'=>150,
     'category_id' => $Puffer->id,
     'sale'=> true
    ],
    ['image' => 'bub2.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>150,
     'new_arrival'=> true,
     'category_id' => $Puffer->id,
      
    ],
    ['image' => 'bub3.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>100,
     'category_id' => $Puffer->id,
    ],
    ['image' => 'bub4.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 130,
     'original_price'=>158,
     'category_id' => $Puffer->id,
     'sale'=> true
    ],
    ['image' => 'bub5.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>220,
     'category_id' => $Puffer->id,
    ],
    ['image' => 'bub6.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>250,
     'new_arrival'=> true,
     'category_id' => $Puffer->id,
    ],
    ['image' => 'bub7.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 80,
     'original_price'=>100,
     'category_id' => $Puffer->id,
     'sale'=> true
    ],

    // Category 6 - Coat
    ['image' => 'coat1.webp', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>250,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat2.webp', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>150,
    'new_arrival'=> true,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat3.webp', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'original_price'=>150,
     'category_id' => $coat->id,
     'sale'=> true
    ],
    ['image' => 'coat4.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>150,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat5.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>100,
    'new_arrival'=> true,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat6.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>150,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat7.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'original_price'=>150,
     'category_id' => $coat->id,
     'sale'=> true
    ],
    ['image' => 'coat8.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>150,
     'new_arrival'=> true,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat9.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>150,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat10.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>180,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat11.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price'=>120,
     'new_arrival'=> true,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat12.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>150,
     'category_id' => $coat->id,
    ],
    ['image' => 'coat13.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price'=>150,
    'new_arrival'=> true,
     'category_id' => $coat->id,
    ],

    // Category 8 - Dresses
    ['image' => 'dres1.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price' => 129,
     'category_id' => $Dresses->id,
    ],
    ['image' => 'dres2.webp', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'original_price'=>180,
     'category_id' => $Dresses->id,
     'sale'=> true
    ],
    ['image' => 'dres3.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price' => 129,
     'category_id' => $Dresses->id,
    ],
    ['image' => 'dres4.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price' => 129,
     'category_id' => $Dresses->id,
    ],

    // Category 9 - Hoodies
    ['image' => 'hodie1.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price' => 129,
     'category_id' => $Hoodies->id,
    ],
    ['image' => 'hodie2.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
       'original_price' => 180,
     'category_id' => $Hoodies->id,
      'sale'=> true
    ],
    ['image' => 'hodie3.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
       'original_price' => 129,
     'category_id' => $Hoodies->id,
    ],
    ['image' => 'hodie4.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price' => 120,
     'category_id' => $Hoodies->id,
    ],
    ['image' => 'hodie5.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
     'category_id' => $Hoodies->id,
    ],
    ['image' => 'hodie6.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'original_price' => 300,
     'category_id' => $Hoodies->id,
    ],
    ['image' => 'hodie7.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
     'category_id' => $Hoodies->id,
    ],

    // Category 10 & 11 - Knitwear
    ['image' => 'kw1.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw2.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw3.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
       'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw4.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
       'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw5.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw6.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw7.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
      'original_price' => 129,
      'new_arrival'=> true,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw8.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
       'original_price' => 300,
     'sale'=>true,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw9.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'new_arrival'=> true,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw10.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
    'original_price' => 129,
     'category_id' => $Knitwear->id,
    ],
    ['image' => 'kw11.jpg', 
     'description' => 'Warm up your winter wardrobe with this stylish piece – made for both comfort and elegance.',
     'price' => 129,
     'original_price' => 300,
     'sale'=>true,
     'category_id' => $Knitwear->id,
    ],
 
];
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
